### PR TITLE
Ship PR for electron-compile 2.0

### PR DESCRIPTION
**Pull request by paulcbetts**
## Compile operations (development mode)

1. Determine if there's a cache hit (requires file contents)
1. For All Compilers
  - Determine if this is a file we should ignore (requires file contents)
  - Determine if any even are interested in this file (requires file contents)
1. Load file contents
1. Compile the file
  - Determine dependent files
  - Compile dependent files
  - Return the contents
1. Save / update cache
1. Compile all of the dependent files
1. Return the contents

* Compilers shouldn't know about compile cache
* Compilers shouldn't explicitly know about node.js registration
* It should be easy to get / set / modify compiler settings
* Inline HTML compiler needs the ability to compile non-file source-code
* Compile file gets context from Determine dependent files?
* Compile needs to return both MIME type info and content
* Compilers should support async

```js
export default class CompilerBase {
  compilerInformation (get/set property)

  static getMimeTypes()

  shouldCompileFile(fileName, compilerContext)
  determineDependentFiles(sourceCode, filePath, compilerContext)
  compile(sourceCode, filePath, compilerContext)
}
```

## TODO:

- [x] Port Inline HTML compiler
- [x] Create top-level compilation of all files by resolving MIME types
- [ ] Try to implement `determineDependentFiles` for LESS and TypeScript, figure out how that's gonna work
- [x] Fix up protocol hook to use async compile methods
- [x] Fix up require
- [x] Port the precompiler / CLI
- [ ] Dox

### CODE REVIEW

**Comment by rgbkrk** [comment]
Wowsers. Thanks as always @paulcbetts.

**Comment by maxkorp** [comment]
Did
> Try to implement determineDependentFiles for LESS and TypeScript, figure out how that's gonna work
get skipped for this one, I'm assuming?

**Comment by paulcbetts** [comment]
@maxkorp Yeah, I set up a lot of the pieces, but I still need to:

1. Write the code in the LESS / TypeScript compiler to dig out imports
1. Use the dependent files in CompilerHost to invalidate CompileCache entries

**Pull request merged**
